version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.14
    - 2.5.9
    - 2.6.0
    - 2.7.0
    - 2.8.2
    - 2.8.3
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: laravel/socialite
    versions:
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.3.0
  - dependency-name: laravel/framework
    versions:
    - 8.22.1
  - dependency-name: laravel/ui
    versions:
    - 3.2.0
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: y18n
    versions:
    - 4.0.1
